service: talkbot-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

functions:
  talkBot:
    handler: src/handlers/contentfulHandler.handler
    events:
      - http:
          path: talkbot
          method: get
          request:
            parameters:
              querystrings:
                contentTypeId: true
                contentEntryKey: false

plugins:
  - serverless-offline

custom:
  serverless-offline:
    stage: ${opt:stage, 'dev'}
    prefix: ""
